In [1]:
import numpy as np

In [2]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [3]:
np.linspace(0,1,2)

array([0., 1.])

In [4]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [5]:
np.linspace(0,np.pi,21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

In [6]:
l = np.array([2,2,6,1,3])

In [7]:
l

array([2, 2, 6, 1, 3])

In [8]:
np.diff(l)

array([ 0,  4, -5,  2])

In [9]:
k = np.array([1,2,3])

In [10]:
k

array([1, 2, 3])

In [11]:
np.diff(k)

array([1, 1])

In [12]:
print(k)

[1 2 3]


In [13]:
a = np.array([1,5,4])
a1 = np.array([1,5,4])
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [14]:
a

array([1, 5, 4])

In [15]:
a1

array([1, 5, 4])

In [16]:
np.concatenate([a,a1])

array([1, 5, 4, 1, 5, 4])

In [17]:
np.concatenate([a,k])

array([1, 5, 4, 1, 2, 3])

In [18]:
b = np.array([[1,2,8],[4,5,8]])

In [19]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [20]:
b1 = np.array([[10],[20]])

In [21]:
b1

array([[10],
       [20]])

In [22]:
np.cpncatenate([b,b1],axis = 1)

AttributeError: module 'numpy' has no attribute 'cpncatenate'

In [23]:
np.concatenate([b,b1],axis = 1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [24]:
np.hstack([b,b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [25]:
c

NameError: name 'no' is not defined

In [26]:
b2 = np.array([30,60,45])

In [27]:
b2

array([30, 60, 45])

In [28]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [29]:
b3 = np.vstack([b,b2])

In [30]:
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [31]:
y = np.vstack([b2,b])

In [32]:
y

array([[30, 60, 45],
       [ 1,  2,  8],
       [ 4,  5,  8]])

In [1]:
b3

NameError: name 'b3' is not defined

In [2]:
import numpy as np

In [3]:
b3

NameError: name 'b3' is not defined

In [4]:
b3 = np.array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [5]:
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [6]:
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [7]:
first, second = np.hsplit(b3,[2])

In [8]:
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [9]:
second

array([[ 8],
       [ 8],
       [45]])

In [10]:
first1, second1 = np.vsplit(b3,[2])

In [11]:
first1

array([[1, 2, 8],
       [4, 5, 8]])

In [12]:
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [13]:
second1

array([[30, 60, 45]])

In [14]:
b = np.array([1,2,8],[4,5,8])

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [15]:
b = np.array([[1,2,8],[4,5,8]])

In [16]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [17]:
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])

In [18]:
a=np.array([1,5,4])

In [19]:
a

array([1, 5, 4])

In [20]:
a[np.newaxis, :]

array([[1, 5, 4]])

In [21]:
a[: , np.newaxis]

array([[1],
       [5],
       [4]])

In [22]:
m = np.arange(0,4)

In [23]:
m

array([0, 1, 2, 3])

In [24]:
n = np.arange(4,7)

In [25]:
n

array([4, 5, 6])

In [26]:
xx, yy = np.meshgrid(m,n)

In [27]:
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [28]:
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In [29]:
np.meshgrid(m,n)

[array([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]),
 array([[4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]])]

In [1]:
import numpy as np

In [2]:
a = np.arange(3)
b = np.arange(-3,3).reshape((2,3))
c = np.arange(1,7).reshape((2,3))
d = np.arange(6).reshape((3,2))
e = np.linspace(-1,1,10)
print('a:', a)
print('b:', b)
print('c:', c)
print('d:', d)
print('e:', e)

a: [0 1 2]
b: [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [3]:
print('a:', a.shape)
print('b:', b.shape)
print('c:', c.shape)
print('d:', d.shape)
print('e:', e.shape)

a: (3,)
b: (2, 3)
c: (2, 3)
d: (3, 2)
e: (10,)


In [4]:
li = [[-3,-2,-1],[0,1,2]]
new = []
for i, j in enumerate(li):
    new.append([])
    for k in i:
        new[i].append(abs(k))
new

TypeError: 'int' object is not iterable

In [5]:
li = [[-3,-2,-1],[0,1,2]]
new = []
for i, j in enumerate(li):
    new.append([])
    for k in j:
        new[i].append(abs(k))
new

[[3, 2, 1], [0, 1, 2]]

In [6]:
li = [[-3,-2,-1],[0,1,2]]
new = []
for i, j in enumerate(li):
    new.append([])
new

[[], []]

In [7]:
li = [[-3,-2,-1],[0,1,2]]
new = []
for i, j in enumerate(li):
    new.append([])
    for k in j:
        new[i].append(abs(k))
new

[[3, 2, 1], [0, 1, 2]]

In [8]:
li = [[-3,-2,-1],[0,1,2]]
new = []
for i, j in enumerate(li):
    new.append([])
    for k in j:
        new[i].append(abs(k))
new

[[3, 2, 1], [0, 1, 2]]

In [9]:
li = [[-3,-2,-1],[0,1,2]]
new = []
for i, j in enumerate(li):
    new.append([])
    for k in i:
        new[j].append(abs(k))
new

TypeError: 'int' object is not iterable

In [10]:
li = [[-3,-2,-1],[0,1,2]]
new = []
for i, j in enumerate(li):
    new.append([])
    for k in j:
        new[i].append(abs(k))
new

[[3, 2, 1], [0, 1, 2]]

In [11]:
li = [[-3,-2,-1],[0,1,2]]
new = []
for i, j in enumerate(li):
    new.append([])
i
j
new

[[], []]

In [12]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [13]:
np.abs(b)

array([[3, 2, 1],
       [0, 1, 2]])

In [14]:
e

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [15]:
np.sin(e)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [16]:
np.cos(e)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [17]:
a

array([0, 1, 2])

In [18]:
np.log(a)

<ipython-input-18-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718])

In [19]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np.log10(c)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [21]:
a

array([0, 1, 2])

In [22]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [23]:
[i % 4 for i in range(20)]

[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]

In [24]:
[i for i in range(20) if i % 2 == 0]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [25]:
a = []
for i in range(20):
    if i % 2 == 0:
        a.append(i)
a

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [26]:
def add(a,b):
    return a + b

In [27]:
add(5,7)

12

In [28]:
add(8,9)

17

In [29]:
def calc(a, b):
    if b == 0:
        return
    return a+b, a-b, a*b, a/b

In [30]:
calc(9,3)

(12, 6, 27, 3.0)

In [31]:
calc(4,2)

(6, 2, 8, 2.0)

In [32]:
calc(3,0)

In [33]:
calc(2,0)

In [34]:
calc(2,2)

(4, 0, 4, 1.0)

In [35]:
n1, n2, n3, n4 = calc(9,3)

n1
n2
n3
n4

3.0

In [36]:
n1

12

In [37]:
calc

<function __main__.calc(a, b)>

In [38]:
n2

6

In [39]:
n3

27

In [40]:
n4

3.0

In [41]:
n1, n2, n3, n4 = calc(9,3)
n1
n2
n3
n4

3.0

In [42]:
n1

12

In [43]:
q = 1,3,5

In [44]:
type(q)

tuple

In [45]:
q

(1, 3, 5)

In [46]:
a = 'python'
b = 'javascript'

In [47]:
a

'python'

In [48]:
b

'javascript'

In [49]:
a,b = b,a

In [50]:
a

'javascript'

In [51]:
b

'python'

In [1]:
import numpy as np


In [2]:
a = np.array([0,1,2])

In [3]:
a

array([0, 1, 2])

In [4]:
a+10

array([10, 11, 12])

In [5]:
b = np.array([[-3,-2,-1],[0,1,2]])

In [6]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [7]:
a

array([0, 1, 2])

In [8]:
b + a

array([[-3, -1,  1],
       [ 0,  2,  4]])

In [9]:
a1 = a[:, np.newaxis]

In [10]:
a1

array([[0],
       [1],
       [2]])

In [11]:
a

array([0, 1, 2])

In [12]:
a + a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [13]:
c = np.array([[1,2,3],[4,5,6]])

In [14]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.mean(c)

3.5

In [16]:
c - np.mean(c)

array([[-2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5]])

In [17]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [18]:
b*2

array([[-6, -4, -2],
       [ 0,  2,  4]])

In [19]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [20]:
b**3

array([[-27,  -8,  -1],
       [  0,   1,   8]], dtype=int32)

In [21]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [22]:
a

array([0, 1, 2])

In [23]:
b-a

array([[-3, -3, -3],
       [ 0,  0,  0]])

In [24]:
 b*a

array([[ 0, -2, -2],
       [ 0,  1,  4]])

In [25]:
a*b

array([[ 0, -2, -2],
       [ 0,  1,  4]])

In [26]:
a

array([0, 1, 2])

In [27]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [28]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a/c

array([[0.        , 0.5       , 0.66666667],
       [0.        , 0.2       , 0.33333333]])

In [31]:
a

array([0, 1, 2])

In [32]:
c/a

<ipython-input-32-03f768c7cd76>:1: RuntimeWarning: divide by zero encountered in true_divide
  c/a


array([[inf, 2. , 1.5],
       [inf, 5. , 3. ]])

In [33]:
c/(a+1e-6)

array([[1.00000000e+06, 1.99999800e+00, 1.49999925e+00],
       [4.00000000e+06, 4.99999500e+00, 2.99999850e+00]])

In [34]:
a

array([0, 1, 2])

In [35]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [1]:
a

NameError: name 'a' is not defined

In [2]:
imprt numpy as np

SyntaxError: invalid syntax (<ipython-input-2-c7cfea7870aa>, line 1)

In [3]:
import numpy as np

In [4]:
a = np.array([0,1,2])

In [5]:
b = np.array([[-3,-2,-1],[0,1,2]])

In [6]:
a

array([0, 1, 2])

In [7]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [8]:
np.dot(b,a)

array([-4,  5])

In [9]:
c = np.array([1,4])

In [10]:
d = np.array([2,3])

In [11]:
np.dot(c,d)

14

In [12]:
a

array([0, 1, 2])

In [13]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [14]:
np.dot(b,a)

array([-4,  5])

In [15]:
b @ a

array([-4,  5])

In [16]:
d = np.array([[0,1],[2,3],[4,5]])

In [17]:
d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
a@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [19]:
b@a

array([-4,  5])

In [20]:
a

array([0, 1, 2])

In [21]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [22]:
d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
b @ d

array([[ -8, -14],
       [ 10,  13]])

In [24]:
d @ b

array([[  0,   1,   2],
       [ -6,  -1,   4],
       [-12,  -3,   6]])

In [25]:
a

array([0, 1, 2])

In [26]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [27]:
a > 1

array([False, False,  True])

In [28]:
b > 0

array([[False, False, False],
       [False,  True,  True]])

In [29]:
np.count_nonzero(b > 0)

2

In [30]:
np.sum(b > 0)

2

In [31]:
np.any(b > 0)

True

In [32]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [33]:
np.any(b > 2)

False

In [1]:
import numpy as np
a = np.array([0,1,2])
b = np.array([[-3,-2,-1],[0,1,2]])
c = np.array([1,4])
d = np.array([2,3])

In [2]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [3]:
np.all(b > 0)

False

In [4]:
b[b > 0]

array([1, 2])

In [5]:
c = np.array([1,2,3],[4,5,6])

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [6]:
c = np.array([[1,2,3],[4,5,6]])

In [7]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b == c

array([[False, False, False],
       [False, False, False]])

In [9]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [10]:
a

array([0, 1, 2])

In [11]:
a == b

array([[False, False, False],
       [ True,  True,  True]])

In [12]:
(b == c) | (a == b)

array([[False, False, False],
       [ True,  True,  True]])

In [13]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [14]:
a

array([0, 1, 2])

In [15]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b[(b == c) | (a == b)]

array([0, 1, 2])

In [17]:
np.allclose(b,c)

False

In [18]:
np.allclose(b,c, atol = 10)

True

In [19]:
np.allclose(b,c, atol = 3)

False

In [20]:
np.allclose(b,c, atol = 10)

True

In [21]:
a

array([0, 1, 2])

In [22]:
a

array([0, 1, 2])

In [23]:
np.sum(a)

3

In [24]:
a.sum()

3

In [25]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [26]:
np.sum(b)

-3

In [27]:
b.sum()

-3

In [1]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.arange(12).reshape(4,3)),
                  columns = ['A','B','C'],
                  index = ['1行目','2行目','3行目','4行目'])
df

IndentationError: unexpected indent (<ipython-input-1-c73a968581da>, line 4)

In [2]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.arange(12).reshape((4,3)),
                  columns = ['A','B','C'],
                  index = ['1行目','2行目','3行目','4行目'])
df

A   B   C
1行目  0   1   2
2行目  3   4   5
3行目  6   7   8
4行目  9  10  11

In [3]:
df['A']

1行目    0
2行目    3
3行目    6
4行目    9
Name: A, dtype: int32

In [4]:
df[['A','B']]

A   B
1行目  0   1
2行目  3   4
3行目  6   7
4行目  9  10

In [5]:
df[:2]

A  B  C
1行目  0  1  2
2行目  3  4  5

In [6]:
df[:1]

A  B  C
1行目  0  1  2

In [7]:
df.loc[:,:]

A   B   C
1行目  0   1   2
2行目  3   4   5
3行目  6   7   8
4行目  9  10  11

In [8]:
df.loc[:, 'A']

1行目    0
2行目    3
3行目    6
4行目    9
Name: A, dtype: int32

In [9]:
df.loc[:, ['A','B']]

A   B
1行目  0   1
2行目  3   4
3行目  6   7
4行目  9  10

In [10]:
df.loc['1行目', :]

A    0
B    1
C    2
Name: 1行目, dtype: int32

A  B  C
1行目  0  1  2
3行目  6  7  8

In [1]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.arange(12).reshape((4,3)),
                  columns = ['A','B','C'],
                  index = ['1行目','2行目','3行目','4行目'])
df

A   B   C
1行目  0   1   2
2行目  3   4   5
3行目  6   7   8
4行目  9  10  11

In [2]:
df.loc[['1行目','4行目'],:]

A   B   C
1行目  0   1   2
4行目  9  10  11

In [3]:
df.loc[['1行目'],['A','C']]

A  C
1行目  0  2

In [4]:
df.iloc[1,1]

4

In [5]:
df.iloc[1:, 1]

2行目     4
3行目     7
4行目    10
Name: B, dtype: int32

In [6]:
df

A   B   C
1行目  0   1   2
2行目  3   4   5
3行目  6   7   8
4行目  9  10  11

In [7]:
df.iloc[1:, :2]

A   B
2行目  3   4
3行目  6   7
4行目  9  10